### ISSUE TITLE
TestRunShutdownHook failed if no ZafiraListener registered

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2129]
2020-04-27 21:22:01 CucumberRunner [main-1] [INFO] Report json: cucumber-json-report.json
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
2020-04-27 21:22:06 Messager [main-1] [INFO] INFO: '**************** Test execution summary ****************'.
2020-04-27 21:22:06 Messager [main-1] [INFO] RESULT #1: TEST [Grip - feature] PASS 
...
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 153.306 s - in TestSuite
2020-04-27 21:22:09 com.qaprosoft.zafira.listener.ZafiraEventRegistrar$TestRunShutdownHook [Thread-4] [INFO]: TestRunShutdownHook was executed with result: true
log4j:ERROR null
java.util.concurrent.TimeoutException
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:622)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:547)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:540)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.close(AutorecoveringChannel.java:73)
	at com.qaprosoft.zafira.log.event.impl.RabbitMQService.releaseConnection(RabbitMQService.java:81)
	at com.qaprosoft.zafira.log.impl.LogAppenderServiceImpl.onClose(LogAppenderServiceImpl.java:87)
	at com.qaprosoft.zafira.log.log4j.LogAppender.onShutdownHook(LogAppender.java:80)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

**Comment by vdelendik** [comment]
with enabled ZafiraListener a little bit different exception:
Exception in thread "Thread-2" com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.processShutdownSignal(AMQChannel.java:401)
	at com.rabbitmq.client.impl.ChannelN.startProcessShutdownSignal(ChannelN.java:292)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:613)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:547)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:540)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.close(AutorecoveringChannel.java:73)
	at com.qaprosoft.zafira.log.event.impl.RabbitMQService.releaseConnection(RabbitMQService.java:81)
	at com.qaprosoft.zafira.log.impl.LogAppenderServiceImpl.onClose(LogAppenderServiceImpl.java:87)
	at com.qaprosoft.zafira.log.log4j.LogAppender.onShutdownHook(LogAppender.java:80)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-4" com.rabbitmq.client.ShutdownSignalException: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:622)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:547)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:540)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.close(AutorecoveringChannel.java:73)
	at com.qaprosoft.zafira.log.event.impl.RabbitMQService.releaseConnection(RabbitMQService.java:81)
	at com.qaprosoft.zafira.log.impl.LogAppenderServiceImpl.onClose(LogAppenderServiceImpl.java:87)
	at com.qaprosoft.zafira.util.upload.DirectAppender.onShutdownHook(DirectAppender.java:54)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.ShutdownSignalException: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:594)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:547)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:540)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.close(AutorecoveringChannel.java:73)
	at com.qaprosoft.zafira.log.event.impl.RabbitMQService.releaseConnection(RabbitMQService.java:81)
	at com.qaprosoft.zafira.log.impl.LogAppenderServiceImpl.onClose(LogAppenderServiceImpl.java:87)
	at com.qaprosoft.zafira.log.log4j.LogAppender.onShutdownHook(LogAppender.java:80)
	... 1 more

**Comment by vdelendik** [comment]
closing as won't fix because new generation of agents don't have direct connection with rabbitmq anymore
