### ISSUE TITLE
1.7: unable to register repository vs new instance due to the "User with id 2 doesn’t exist"

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2180]
After installing fresh 1.7 reporting tool in scope of infra I can't register any repository launchers because reporting service tries to find user from postgres database.
User with id=2 exists only in iam-db as of now.

```
2020-07-27 15:50:26.478 ERROR [http-nio-8080-exec-4] c.z.r.web.ApiExceptionHandler: User with id 2 doesn’t exist
com.zebrunner.reporting.service.exception.ResourceNotFoundException: User with id 2 doesn’t exist
	at com.zebrunner.reporting.service.UserService.getNotNullById(UserService.java:36)
	at com.zebrunner.reporting.service.UserService$$FastClassBySpringCGLIB$$f0c4dc3d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.zebrunner.reporting.service.UserService$$EnhancerBySpringCGLIB$$85f97b31.getNotNullById(<generated>)
	at com.zebrunner.reporting.service.LauncherService.buildScannerJob(LauncherService.java:297)
	at com.zebrunner.reporting.service.LauncherService$$FastClassBySpringCGLIB$$4a258d48.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.zebrunner.reporting.service.LauncherService$$EnhancerBySpringCGLIB$$cf410d32.buildScannerJob(<generated>)
	at com.zebrunner.reporting.web.LauncherController.runScanner(LauncherController.java:124)
```

**Comment by vdelendik** [comment]
the same issue reproduced during tests registration
[tests-registration.log](https://github.com/zebrunner/zebrunner/files/4983238/tests-registration.log)

**Comment by vdelendik** [comment]
fixed indirectly

**Comment by okamara** [comment]
Tested on qps-infra develop 5.1 reporting 1.8. Fixed.
