### ISSUE TITLE
Launcher is faild as "TestRun is not found in Zafira!"

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2242]
**Steps to reproduce**
Setup zebrunner CE:
1. Go to 'Reporting'
2. Click on 'Test Launcher'
3. Open carina-demo repo
4. Run Web test or API test

**Actual behavior**
Launcher in Jenkins is failed. No Test run report in Reporting
**Expected behavior (if known)**
Launcher in Jenkins is Passed. Test run report is in Reporting

**Environment**
UI version:1.12
API (back-end) version:1.12.1

**Comment by okamara** [comment]
Verified on dev. Fixed.

**Comment by dhreben** [comment]
**Steps to reproduce**

Setup zebrunner CE:

1.Go to 'Reporting'
2.Click on 'Test Launcher'
3.Open carina-demo repo
4.Run Web test or API test

**Actual result** : Launcher in Jenkins is failed. No Test run report in Reporting


**Environment:**
develop branch
UI version: 1.14.0.RC1

```

screen_record_ftp=ftp://${INFRA_HOST}/%s.mp4
[Pipeline] echo
screen_record_user=qpsdemo
[Pipeline] echo
screen_record_pass=qpsdemo
[Pipeline] echo
screen_record_duration=1800
[Pipeline] echo
s3_save_screenshots=true
[Pipeline] echo
vnc_desktop=%s://%s:%s/vnc/%s
[Pipeline] echo
vnc_mobile=%s://%s:%s/websockify
[Pipeline] echo
vnc_protocol=ws
[Pipeline] echo
vnc_host=${INFRA_HOST}
[Pipeline] echo
vnc_port=80
[Pipeline] echo
capabilities.enableVNC=true
[Pipeline] echo
capabilities.enableVideo=true
[Pipeline] echo
capabilities.STF_ENABLED=false
[Pipeline] echo
user.timezone=UTC
[Pipeline] echo
s3_local_storage=/opt/apk
[Pipeline] echo
appcenter_local_storage=/opt/apk
[Pipeline] echo
BROWSERSTACK_ACCESS_KEY=********
[Pipeline] echo
TESTRAIL_SERVICE_URL=
[Pipeline] echo
TESTRAIL_USERNAME=
[Pipeline] echo
TESTRAIL_PASSWORD=********
[Pipeline] echo
QTEST_SERVICE_URL=
[Pipeline] echo
QTEST_ACCESS_TOKEN=********
[Pipeline] echo
DOCKER_HUB_USERNAME={must_override}
[Pipeline] echo
DOCKER_HUB_PASSWORD={must_override}
[Pipeline] echo
PARAMS:
[Pipeline] echo
repoURL=repository url (read permissions is enough)
[Pipeline] echo
ci_run_id=a97f264b-4df1-49e4-bb3f-ba245a527fca
[Pipeline] echo
queue_registration=false
[Pipeline] echo
rerun_failures=false
[Pipeline] echo
branch=master
[Pipeline] echo
suite=api
[Pipeline] echo
zafiraFields=capabilities.platformName=API,suite=api,selenium_url=http://demo:demo@54.204.162.187:80/selenoid/wd/hub,capabilities.provider=SELENIUM,zafira_enabled=true,zafira_service_url=http://54.204.162.187:80,zafira_access_token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwicGFzc3dvcmQiOiIxbjEveDFJTktBZG11aTZEc3VOWUFzSUg2SS9WcU12QSIsImV4cCI6Mzc1MTU3MTA2NH0.N2C7w4S6SgeGAlx3bc-VRObA5_FqEl6CAuLoD9wugTlULrmKMWg_WeGeU8iJ4hyNgyvjLaFipAygpdCdvCyCZQ
[Pipeline] echo
capabilities.platformName=API
[Pipeline] echo
zafira_enabled=true
[Pipeline] echo
zafira_service_url=http://54.204.162.187:80
[Pipeline] echo
zafira_access_token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwicGFzc3dvcmQiOiIxbjEveDFJTktBZG11aTZEc3VOWUFzSUg2SS9WcU12QSIsImV4cCI6Mzc1MTU3MTA2NH0.N2C7w4S6SgeGAlx3bc-VRObA5_FqEl6CAuLoD9wugTlULrmKMWg_WeGeU8iJ4hyNgyvjLaFipAygpdCdvCyCZQ
[Pipeline] echo
jobName: launcher
[Pipeline] echo
nameCount: 1
[Pipeline] echo
orgFolderName: 
[Pipeline] echo
[INFO] TestNG->runJob
[Pipeline] echo
[INFO] UUID: a97f264b-4df1-49e4-bb3f-ba245a527fca
[Pipeline] httpRequest
HttpMethod: POST
URL: http://54.204.162.187:80/api/iam/v1/auth/refresh
Content-Type: application/json
Sending request to url: http://54.204.162.187:80/api/iam/v1/auth/refresh
Response Code: HTTP/1.1 200 
Success code from [200‥404]
[Pipeline] httpRequest
HttpMethod: GET
URL: http://54.204.162.187:80/api/reporting/api/tests/runs?ciRunId=a97f264b-4df1-49e4-bb3f-ba245a527fca
Content-Type: application/json
Authorization: *****
Sending request to url: http://54.204.162.187:80/api/reporting/api/tests/runs?ciRunId=a97f264b-4df1-49e4-bb3f-ba245a527fca
Response Code: HTTP/1.1 404 
Success code from [200‥404]
[Pipeline] node
Running on Jenkins in /var/jenkins_home/jobs/launcher/workspace
[Pipeline] {
[Pipeline] echo
[INFO] Suite Type: Default
[Pipeline] echo
[INFO] nodeLabel: null
[Pipeline] echo
[INFO] node: default
[Pipeline] }
[Pipeline] // node
[Pipeline] node
Running on jenkins-slave in /opt/jenkins/workspace/launcher
[Pipeline] {
[Pipeline] wrap
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Preparation)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Checkout Repository)
[Pipeline] echo
22:50:33  [INFO] Git->clone; shallow: true
[Pipeline] echo
22:50:33  [INFO] REPO_URL: null
[Pipeline] echo
22:50:33  [INFO] CREDENTIALS_ID: null
[Pipeline] checkout
22:50:33  The recommended git tool is: NONE
22:50:35  No credentials specified
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] echo
[ERROR] hudson.AbortException: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1152)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1298)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[Pipeline] httpRequest
22:50:35   > git rev-parse master^{commit} # timeout=10
HttpMethod: GET
URL: http://54.204.162.187:80/api/reporting/api/tests/runs?ciRunId=a97f264b-4df1-49e4-bb3f-ba245a527fca
Content-Type: application/json
Authorization: *****
Sending request to url: http://54.204.162.187:80/api/reporting/api/tests/runs?ciRunId=a97f264b-4df1-49e4-bb3f-ba245a527fca
Response Code: HTTP/1.1 404 
Success code from [200‥404]
[Pipeline] echo
[ERROR] TestRun is not found in Zafira!
[Pipeline] stage
[Pipeline] { (Results)
[Pipeline] findFiles
[Pipeline] findFiles
[Pipeline] findFiles
[Pipeline] findFiles
[Pipeline] findFiles
[Pipeline] findFiles
[Pipeline] findFiles
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Wipe out Workspace)
[Pipeline] deleteDir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // wrap
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Finished: FAILURE

```

**Comment by vdelendik** [comment]
it should be fixed already in zebrunnre/zebrunner (branch: develop)

**Comment by dhreben** [comment]
Verified on dev. Fixed.
