### ISSUE TITLE
Issues with start reporting service

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2266]
Env.: Env.: ui: 1.16.0.RC3
server: 1.16.0.RC1 

Steps:
1.  Install and start Jenkins, Reporting
Actual result: Reporting is start with errors in console and 500 error on the page
Console log:
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name ‘freemarkerUtil’: Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder ‘TEMPLATES_DIRECTORY’ in value “${TEMPLATES_DIRECTORY}”
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:405)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
	... 70 common frames omit

**Comment by vdelendik** [comment]
fixed. new TEMPLATES_DIRECTORY variable declared in reporting-service/variables.env
Also patch 1.3.sh script for upgrade adjusted accordingly

**Comment by okamara** [comment]
I see TEMPLATES_DIRECTORY=templates, but I can't sign in to reporting.
