### ISSUE TITLE
backup/restore might corrupt elasticsearch data

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2294]
After removal of the esdata-volume docker volume we couldn't restore data. 
It seems like permissions should be synced during restore
```
ElasticsearchException[failed to load metadata]; nested: CorruptIndexException[file mismatch, expected id=diel8n48ntdbqfgj1c39n5zli, got=g8ymw42mi2oudvx2pdybmapk (resource=BufferedChecksumIndexInput(SimpleFSIndexInput(path="/usr/share/elasticsearch/data/nodes/0/_state/_3.si")))];
Likely root cause: org.apache.lucene.index.CorruptIndexException: file mismatch, expected id=diel8n48ntdbqfgj1c39n5zli, got=g8ymw42mi2oudvx2pdybmapk (resource=BufferedChecksumIndexInput(SimpleFSIndexInput(path="/usr/share/elasticsearch/data/nodes/0/_state/_3.si")))
        at org.apache.lucene.codecs.CodecUtil.checkIndexHeaderID(CodecUtil.java:351)
        at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:256)
        at org.apache.lucene.codecs.lucene86.Lucene86SegmentInfoFormat.read(Lucene86SegmentInfoFormat.java:95)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:357)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291)
        at org.apache.lucene.index.IndexFileDeleter.<init>(IndexFileDeleter.java:165)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:951)
        at org.elasticsearch.gateway.PersistedClusterStateService.createIndexWriter(PersistedClusterStateService.java:204)
        at org.elasticsearch.gateway.PersistedClusterStateService.createWriter(PersistedClusterStateService.java:180)
        at org.elasticsearch.gateway.GatewayMetaState$LucenePersistedState.<init>(GatewayMetaState.java:490)
        at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:165)
        at org.elasticsearch.node.Node.start(Node.java:786)
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:317)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:402)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
For complete error details, refer to the log at /usr/share/elasticsearch/logs/elasticsearch.log
```

**Comment by vdelendik** [comment]
closing as can't reproduce
